apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-tls-configmap
data:
  mq-tls.mqsc: |
    DEFINE CHANNEL('MQ.CLIENT.SVRCONN') CHLTYPE(SVRCONN) SSLCAUTH(REQUIRED) SSLCIPH('ANY_TLS13_OR_HIGHER') REPLACE
    SET CHLAUTH('MQ.CLIENT.SVRCONN') TYPE(SSLPEERMAP) SSLPEER('CN=*') USERSRC(NOACCESS) ACTION(REPLACE)
    SET CHLAUTH('MQ.CLIENT.SVRCONN') TYPE(SSLPEERMAP) SSLPEER('CN=mqclient') USERSRC(MAP) MCAUSER('mqclient') ACTION(REPLACE)
    SET AUTHREC PRINCIPAL('mqclient') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ)
    DEFINE QLOCAL('DEMO.QUEUE') REPLACE 
    SET AUTHREC PROFILE('DEMO.QUEUE') PRINCIPAL('mqclient') OBJTYPE(QUEUE) AUTHADD(BROWSE,PUT,GET,INQ)
    SET CHLAUTH('MQ.CLIENT.SVRCONN') TYPE(SSLPEERMAP) SSLPEER('CN=aceclient') USERSRC(MAP) MCAUSER('aceclient') ACTION(REPLACE)
    SET AUTHREC PRINCIPAL('aceclient') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE('DEMO.QUEUE') PRINCIPAL('aceclient') OBJTYPE(QUEUE) AUTHADD(BROWSE,PUT,GET,INQ)
  mq-tls.ini: |
    Service:
        Name=AuthorizationService
        EntryPoints=14
        SecurityPolicy=UserExternal
